services:
  mysql:
    restart: always
    privileged: true
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Qkxc123456
    volumes:
      - /opt/mes/mysql/log:/var/log/mysql # 映射日志目录，宿主机:容器
      - /opt/mes/mysql/data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - /opt/mes/mysql/conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
      - /etc/localtime:/etc/localtime:ro # 让容器的时钟与宿主机时钟同步，避免时间的问题，ro是read only的意思，就是只读。
    networks:
      - jiqid_net

  redis:
    restart: always
    privileged: true
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /opt/mes/redis/data:/data
    command: [ "redis-server", "--requirepass", "Qkxc123456" ]
    networks:
      - jiqid_net

  nginx:
    restart: always
    privileged: true
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    volumes:
      - ./deploy/backend/nginx.conf:/etc/nginx/nginx.conf
      - /opt/mes/nginx/html:/usr/share/nginx/html
      - /opt/mes/nginx/logs:/var/log/nginx
    networks:
      - jiqid_net

networks:
  jiqid_net:
    driver: bridge