; ======================
;  服务 - Alpha环境
; ======================
[program:mes_alpha_8000]
directory       = /opt/mes/alpha/mespy/backend
command         = /opt/mes/alpha/mespy/.venv/bin/granian main:app --interface asgi --host 0.0.0.0 --port 8000 --workers 1 --runtime-threads 2 --backlog 1024 --workers-kill-timeout 120 --backpressure 2000 --no-reload --log --log-level debug
user            = root
autostart       = true
autorestart     = true
startretries    = 5
redirect_stderr = true
stdout_logfile  = /opt/mes/deploy_logs/mes_alpha_8000.log
stdout_logfile_maxbytes = 5MB
stdout_logfile_backups  = 5

; ======================
;  服务 - Prod环境
; ======================
[program:mes_prod_8100]
directory       = /opt/mes/prod/mespy/backend
command         = /opt/mes/prod/mespy/.venv/bin/granian main:app --interface asgi --host 0.0.0.0 --port 8100 --workers 1 --runtime-threads 2 --backlog 1024 --workers-kill-timeout 120 --backpressure 2000 --no-reload --log --log-level debug
user            = root
autostart       = true
autorestart     = true
startretries    = 5
redirect_stderr = true
stdout_logfile  = /opt/mes/deploy_logs/mes_alpha_8000.log
stdout_logfile_maxbytes = 5MB
stdout_logfile_backups  = 5

; ======================
; celery worker - Alpha环境
; ======================
[program:mes_alpha_celery_worker]
directory       = /opt/mes/alpha/mespy/backend
command         = /opt/mes/alpha/mespy/.venv/bin/celery -A app.task.celery worker -P gevent -c 1000 --loglevel=INFO
user            = root
autostart       = true
autorestart     = true
startretries    = 5
redirect_stderr = true
stdout_logfile  = /opt/mes/deploy_logs/mes_alpha_celery_worker.log
stdout_logfile_maxbytes = 5MB
stdout_logfile_backups  = 5

; ======================
; celery beat - Alpha环境
; ======================
[program:mes_alpha_celery_beat]
directory       = /opt/mes/alpha/mespy/backend
command         = /opt/mes/alpha/mespy/.venv/bin/celery -A app.task.celery beat --loglevel=INFO
user            = root
autostart       = true
autorestart     = true
startretries    = 5
redirect_stderr = true
stdout_logfile  = /opt/mes/deploy_logs/mes_alpha_celery_beat.log
stdout_logfile_maxbytes = 5MB
stdout_logfile_backups  = 5

; ======================
; celery worker - Prod环境
; ======================
[program:mes_prod_celery_worker]
directory       = /opt/mes/prod/mespy/backend
command         = /opt/mes/prod/mespy/.venv/bin/celery -A app.task.celery worker -P gevent -c 1000 --loglevel=INFO
user            = root
autostart       = true
autorestart     = true
startretries    = 5
redirect_stderr = true
stdout_logfile  = /opt/mes/deploy_logs/mes_prod_celery_worker.log
stdout_logfile_maxbytes = 5MB
stdout_logfile_backups  = 5

; ======================
; celery beat - Prod环境
; ======================
[program:mes_prod_celery_beat]
directory       = /opt/mes/prod/mespy/backend
command         = /opt/mes/prod/mespy/.venv/bin/celery -A app.task.celery beat --loglevel=INFO
user            = root
autostart       = true
autorestart     = true
startretries    = 5
redirect_stderr = true
stdout_logfile  = /opt/mes/deploy_logs/mes_prod_celery_beat.log
stdout_logfile_maxbytes = 5MB
stdout_logfile_backups  = 5


; ======================
; 服务组
; sudo supervisorctl start mes_services:   # 启动组内所有服务
; sudo supervisorctl stop mes_services:    # 停止组内所有服务
; sudo supervisorctl restart mes_services: # 重启组内所有服务
; ======================
[group:mes_services]
programs    = mes_alpha_8000, mes_prod_8100, mes_alpha_celery_worker, mes_alpha_celery_beat, mes_prod_celery_worker, mes_prod_celery_beat
priority    = 900